### 체크아웃 API
POST http://localhost:8080/apis/checkout
Content-Type: application/json

{
  "discountId": 1,
  "storeId": 1,
  "customerId": 1
}

### 체크아웃 아이템 조회 API
GET http://localhost:8081/apis/checkout?customerId=1
