spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    username: snow
    password: snow
    url: jdbc:mysql://localhost:13306/food_delivery?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver